#!/bin/bash
# ubuntu setup script - developed by acidvegas (https://git.acid.vegas/void)

# note: After importing keys: printf "FINGERPRINTHERE:6:" | gpg --import-ownertrust

# Set xtrace, exit on error, & verbose mode
set -xev

# Configuration
GIT_URL="https://raw.githubusercontent.com/acidvegas/void/master"
GPG_ID=$(gpg --list-keys --with-colons acidvegas | awk -F: '$1=="fpr"{print $10; exit}')
HOSTNAME="deathstar"

setup_packages() {
	# Install GUI dependant packages
	sudo apt install -y firefox kitty redshift
	sudo apt install -y fonts-noto-core fonts-noto-extra fonts-noto-cjk fonts-noto-color-emoji fonts-dejavu fonts-freefont-ttf
	sudo apt install -y eyed3 rhythmbox

	# Install development packages
	sudo apt install -y ansible python3 python3-pip

	# Install essential packages
	sudo apt install -y curl delta fzf git jq progress rsync tmux tree unzip whois zip

	# Install networking packages
	sudo apt install -y tor wireguard wireguard-tools

	# Install reconnaissance packages
	sudo apt install -y masscan mitmproxy netcat-openbsd nmap strace tcpdump termshark tshark wireshark

	# Install tailscale
	curl -fsSL https://tailscale.com/install.sh | sh

	# Install Docker
	curl -fsSL https://get.docker.com | sh
	sudo gpasswd -a $USER docker

	# Install Github builds
	git clone --depth 1 https://github.com/AngelJumbo/lavat.git /tmp/lavat && sudo make -C /tmp/lavat clean install && rm -rf /tmp/lavat
	git clone --depth 1 https://github.com/lptstr/fire.git      /tmp/fire  && sudo make -C /tmp/fire  clean install && rm -rf /tmp/fire
	git clone --depth 1 https://github.com/ricoriedel/wipe      /tmp/wipe  && sudo cargo build --release --manifest-path /tmp/wipe/Cargo.toml && rm -rf /tmp/wipe
}

setup_root() {
	# Setup hostname
	hostnamectl set-hostname $HOSTNAME

	# Setup Bash
	printf "[[ \$- != *i* ]] && return\nshopt -s checkwinsize\nexport EDITOR=nano\nexport VISUAL=nano\nexport HISTCONTROL=ignoredups\nexport HISTFILE=/dev/null\nexport HISTFILESIZE=0\nexport HISTSIZE=100\nexport LESSHISTFILE=/dev/null\nexport PYTHONHISTFILE=/dev/null" > /etc/bash.bashrc

	# Setup Nano
	printf "set boldtext\nset minibar\nset nohelp\nset nowrap\nset quickblank\nset tabsize 4\nunbind ^J main\nset selectedcolor black,red\ninclude \"/usr/share/nano/*.nanorc\"\n" | sudo tee /etc/nanorc > /dev/null

	# Setup Sudoers
	printf "Defaults lecture = always\nDefaults lecture_file = /etc/sudoers.d/sudoers.lecture\nroot ALL=(ALL) ALL\n%%sudo ALL=(ALL) ALL\n" | sudo tee /etc/sudoers > /dev/null
	printf "\n\033[1m     \033[32m\"Bee\" careful    \033[34m__\n       \033[32mwith sudo!    \033[34m// \ \n                     \\\\\\_/ \033[33m//\n   \033[35m''-.._.-''-.._.. \033[33m-(||)(')\n                     '''\033[0m\n" | sudo tee /etc/sudoers.d/sudoers.lecture > /dev/null
}

setup_user() {
	# Setup Bash
	mkdir -p $HOME/.local/share/bash
	for item in bash_aliases bash_functions bash_fun bash_recon; do
		wget -O $HOME/.local/share/bash/$item $GIT_URL/local/share/bash/$item
	done
	wget -O $HOME/.bashrc $GIT_URL/.bashrc

	# Setup Git
	mkdir -p $HOME/.config/git && wget -O $HOME/.config/git/config $GIT_URL/config/git/config
	sed -i "s|CHANGEME|$GPG_ID|" $HOME/.config/git/config

	# Setup GPG
	mkdir -p $HOME/.local/share/gnupg
	echo "default-key $GPG_ID" > $HOME/.local/share/gnupg/gpg.conf
	printf "pinentry-program /usr/bin/pinentry-curses\ndefault-cache-ttl 3600" > $HOME/.local/share/gnupg/gpg-agent.conf
	chmod 700 $HOME/.local/share/gnupg && chmod 600 $HOME/.local/share/gnupg/*

	# Setup Packages
	wget -O $HOME/.local/bin/cursor https://downloader.cursor.sh/linux/appImage/x64
	chmod u+x $HOME/.local/bin/cursor

	OBSIDIAN_VERSION=$(curl -s https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest | jq -r .tag_name  | cut -c2-)
	wget -O $HOME/.local/bin/obsidian https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_VERSION}/Obsidian-${OBSIDIAN_VERSION}.AppImage
	chmod u+x $HOME/.local/bin/obsidian

	# Setup Pip
	mkdir -p $HOME/.config/pip && printf "[global]\nbreak-system-packages = true" > ~/.config/pip/pip.conf
	python3 -m pip install aiodns aiofiles aioftp aiohttp aiokafka aiormq aiosocks apv beautifulsoup4 cryptography dnspython elasticsearch flask gitpython meshtastic python-dotenv python-socks scapy tqdm websockets


	# Setup Scripts
	mkdir -p $HOME/.local/bin/scripts
	for SCRIPT in gitremote irc-post-commit-hook mutag; do
		wget -O $HOME/.local/bin/scripts/$SCRIPT $GIT_URL/scripts/$SCRIPT
	done

	# Setup Redshift
	(crontab -l 2>/dev/null; echo "0 23 * * * DISPLAY=:0 redshift -P -O 4000"; echo "0 7 * * * DISPLAY=:0 redshift -x") | crontab -

	# Setup Tmux
	mkdir -p $HOME/.config/tmux && wget -O $HOME/.config/tmux/tmux.conf $GIT_URL/config/tmux/tmux.conf
	sed -i "s|/dev/sda2|$(df $HOME | awk 'NR==2 {print $1}')|" $HOME/.config/tmux/tmux.conf


	# Remove any line with HISTCONTROL starting it
	sed -i '/HISTCONTROL/d' $HOME/.bashrc
}

[ $# -eq 0         ] && echo "Usage: setup <packages|root|user>" && exit 1
[ $1 != "packages" ] && [ $1 != "root" ] && [ $1 != "user" ] && echo "Invalid argument: $1" && exit 1

setup_$1