#!/bin/sh
# VPS Setup Script - Developed by acidvegas (https://git.acid.vegas)

# Set xtrace, exit on error, & verbose mode
set -xev

GIT_URL="https://raw.githubusercontent.com/acidvegas/void/master"

# Configuration
USERNAME="acidvegas"
HOSTNAME="vps"
PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ/fz4INjgCmSZOUiE9HL3+YRalyF/ptk1+qybcBCwUp"

# Install packages
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt clean
sudo apt install -y curl dnsutils gcc git htop jq make nano ncdu net-tools python3 python-pip rsync screen sudo wget
curl -fsSL https://get.docker.com | sh && sudo gpasswd -a $USER docker

# Setup hostname
sudo hostnamectl set-hostname $HOSTNAME

# Setup time
sudo timedatectl set-timezone UTC && sudo timedatectl set-ntp true

# Setup Bash
printf "[[ \$- != *i* ]] && return\nshopt -s checkwinsize\nexport EDITOR=nano\nexport VISUAL=nano\nexport HISTFILE=/dev/null\nexport HISTFILESIZE=0\nexport HISTSIZE=100\nexport LESSHISTFILE=/dev/null\nexport PYTHONHISTFILE=/dev/null" | sudo tee /etc/bash.bashrc > /dev/null
mkdir -p $HOME/.local/share/bash
for item in bash_aliases bash_functions bash_fun bash_recon; do
	wget -O $HOME/.local/share/bash/$item $GIT_URL/local/share/bash/$item
done
wget -O $HOME/.bashrc $GIT_URL/.bashrc
sed -i '/HISTCONTROL/d' $HOME/.bashrc

# Setup Nano
printf "set boldtext\nset minibar\nset nohelp\nset nowrap\nset quickblank\nset tabsize 4\nunbind ^J main\nunbind ^L main\nset selectedcolor black,red\ninclude \"/usr/share/nano/*.nanorc\"\n" | sudo tee /etc/nanorc > /dev/null

# Setup Journal
printf "[Journal]\nStorage=volatile\nSplitMode=none\nRuntimeMaxUse=500K" | sudo tee /etc/systemd/journald.conf > /dev/null
sudo systemctl stop systemd-journald && sudo rm -rf /var/log/journal && sudo systemctl start systemd-journald

# Setup SSH
RANDOM_PORT=$(shuf -i 1024-65535 -n 1)
printf "AuthenticationMethods publickey\nBanner /etc/issue\nClientAliveInterval 0\nDisableForwarding yes\nPermitRootLogin no\nPort $RANDOM_PORT\nPrintLastLog no" | sudo tee /etc/ssh/sshd_config > /dev/null
mkdir -p $HOME/.ssh && echo $PUBKEY > $HOME/.ssh/authorized_keys && chmod 700 $HOME/.ssh && chown -R $USERNAME $HOME/.ssh && chmod 400 $HOME/.ssh/authorized_keys
echo "SSH Port: $RANDOM_PORT"

# Setup sudoers
printf "Defaults lecture = always\nDefaults lecture_file = /etc/sudoers.d/sudoers.lecture\nroot ALL=(ALL) ALL\n%%sudo ALL=(ALL) ALL\n" | sudo tee /etc/sudoers > /dev/null
printf "\n\033[1m     \033[32m\"Bee\" careful    \033[34m__\n       \033[32mwith sudo!    \033[34m// \ \n                     \\\\\\_/ \033[33m//\n   \033[35m''-.._.-''-.._.. \033[33m-(||)(')\n                     '''\033[0m\n" | sudo tee /etc/sudoers.d/sudoers.lecture > /dev/null

# Setup MOTD
git clone --depth 1 https://github.com/bartobri/no-more-secrets /tmp/nms && sudo make -C /tmp/nms clean all install && sudo rm -rf /tmp/nms
printf "clear && ((echo && printf \"   E N T E R   T H E   V O I D\n\"  && echo) | nms -af red) && cat /etc/motd" | sudo tee /etc/profile.d/motd.sh > /dev/null && sudo chmod +x /etc/profile.d/motd.sh
sudo wget -O /etc/motd $GIT_URL/local/share/art/supernets.txt

# Setup Tmux
mkdir -p $HOME/.config/tmux && wget -O $HOME/.config/tmux/tmux.conf $GIT_URL/config/tmux/tmux.conf
wget -O $HOME/.local/bin/tmux-session-menu $GIT_URL/local/bin/tmux-session-menu && chmod u+x $HOME/.local/bin/tmux-session-menu

# Setup Pip
mkdir -p $HOME/.config/pip && printf "[global]\nbreak-system-packages = true" > ~/.config/pip/pip.conf
