#!/bin/sh
# .bash_aliases - developed by acidvegas (https://git.acid.vegas/void)

# colors
alias diff='diff --color=auto'
alias dmesg='dmesg --color=auto'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'
alias ncdu='ncdu --color dark -rr'
alias tree='tree -C'
alias vdir='vdir --color=auto'

# rewrites
alias cp='cp -i'
alias mv='mv -i'
alias pip='pip3'
alias progress='progress -m'
alias python='python3'
alias tmux='/usr/bin/tmux attach -d 2>/dev/null || /usr/bin/tmux new'
alias vlock='vlock -a'
alias wget='wget -q --show-progress --no-hsts'

# copy & paste
alias ctrlc="xclip -selection clipboard"
alias ctrlv="xclip -selection clipboard -o"

# eza
alias eza='eza --icons'
alias ezal='eza -la --icons --git --group-directories-first'
alias ezat='eza --tree --icons --level=2'

# random
alias ..="cd ../"
alias dump='setterm -dump 1 -file screen.dump'
alias rmcommits="git checkout --orphan new && git add -A && git commit -m 'Initial commit' && git branch -D main && git branch -m main && git push -f origin main"
alias up='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt clean'