#!/bin/sh
# .bash_fun - developed by acidvegas (https://git.acid.vegas/void)

alias ansi='python3 $HOME/.local/bin/scripts/irc2ansi.py $HOME/.local/share/ircart/ircart/ansi'
alias ascii='python3 $HOME/.local/bin/scripts/irc2ansi.py $HOME/.local/share/ircart/ircart/ircart'
alias busy="cat /dev/urandom | hexdump -C | grep 'ca fe'"
alias cmatrix='cmatrix -ab -u 1 -C magenta -s'
alias crypto="curl rate.sx"
alias donut="curl ascii.live/donut"
alias emoji="curl -sSL 'https://git.io/JXXO7' | fzf"
alias lavat='lavat -c magenta -s 10 -r 1 -R 1 -k cyan -b 20'
alias mapscii='telnet mapscii.me'
alias rmatrix='cmatrix -ab -u 1 -C red'
alias pokemon='curl pkmn.li'
alias starwars='telnet towel.blinkenlights.nl'
alias wh='curl wttr.in'

scene() {
	for x in $(curl -L -k -s http://www.textfiles.com/artscene/ansi/bbs/ | tr ' ' '\n' | grep HREF | tr '"' ' ' | awk '{print $2}' | grep -P "(ans|vt)" | grep -v ".png" | grep "." | shuf); do
		curl -L -k -s http://www.textfiles.com/artscene/ansi/bbs/$x | iconv -f 437 -t utf-8 | pv -q -L 600
	done
}

# Some of the commands below are from package installs or custom builds
fun() {
	echo "COMMAND       | DESCRIPTION"
	echo "------------- | -----------"
	echo "asciiquarium  | Terminal-based aquarium"
	echo "ansi          | Play ANSI art in your terminal"
	echo "ascii         | Play ASCII art in your terminal"
	echo "busy          | Make your terminal busy"
	echo "cmatrix       | Matrix-style animation"
	echo "crypto        | Show cryptocurrency rates"
	echo "donut         | Spinning donut"
	echo "dvd           | Bouncing DVD logo"
	echo "fire          | Fire animation"
	echo "lavat         | Lava lamp style animation"
	echo "mapscii       | Maps in your terminal"
	echo "pokemon       | Random Pokémon"
	echo "scene         | Play ANSI scene art in your terminal"
	echo "starwars      | Watch Star Wars in your terminal"
	echo "tty-solitaire | Play solitaire in your terminal"
	echo "wh            | Weather in your terminal"
	echo "wipe          | Clear your terminal in style"
}
