#!/bin/bash
# .bash_functions - developed by acidvegas (https://git.acid.vegas/void)

cheat() {
	curl cht.sh/$1
}

color() {
	for color in {0..255}; do
		printf "\e[48;5;%sm  %3s  \e[0m" $color $color
		if [ $((($color + 1) % 6)) == 4 ]; then
			echo
		fi
	done
}

cctain() {
	NAME=$1
	incus storage create $NAME-pool dir
	incus launch images:debian/12 $NAME-container -s $NAME-pool
	incus config set $NAME-container boot.autostart true
	sleep 10 # Delay to allow the container to start and get an IP address from the DHCP server
	incus exec $NAME-container -- apt update  -y
	incus exec $NAME-container -- apt upgrade -y
	incus exec $NAME-container -- apt install -y git nano unattended-upgrades wget
	incus exec $NAME-container -- useradd -m -s /bin/bash agent
	incus exec $NAME-container -- journalctl --vacuum-time=1d
	incus exec $NAME-container -- sh -c 'printf "[Journal]\nStorage=volatile\nSplitMode=none\nRuntimeMaxUse=500K" > /etc/systemd/journald.conf'
	incus exec $NAME-container -- systemctl restart systemd-journald
}

fkill() {
	local pid
	if [ "$UID" != "0" ]; then
		pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
	else
		pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
	fi
	if [ "x$pid" != "x" ]; then
		echo $pid | xargs kill -${1:-9}
	fi
}

extract() {
	if [ ! -z "$1" ]; then
		if [ -f $1 ]; then
			case $1 in
				*.7z)      7z x $1          ;;
				*.bz2)     bunzip2 $1       ;;
				*.deb)     dpkg-deb -x $1 . ;;
				*.gz)      gunzip $1        ;;
				*.iso)     bsdtar -xf $1    ;;
				*.lz4)     lz4 -d $1        ;;
				*.lzip)    lzip -d $1       ;;
				*.lzma)    unlzma $1        ;;
				*.rar)     unrar x -ad $1   ;;
				*.tar)     tar xvf $1       ;;
				*.tar.bz2) tar xvjf $1      ;;
				*.tar.gz)  tar xvzf $1      ;;
				*.tar.xz)  tar xvJf $1      ;;
				*.tbz2)    tar xvjf $1      ;;
				*.tgz)     tar xvzf $1      ;;
				*.xpi)     unzip $1         ;;
				*.xz)      unxz $1          ;;
				*.Z)       uncompress $1    ;;
				*.zip)     unzip $1         ;;
				*.zst)     unzstd $1        ;;
				*)         echo "$1 - unknown archive format" ;;
			esac
		else
			echo "$1 - file does not exist"
		fi
	fi
}

flash() {
	sudo dd bs=4M if=$1 of=$2 status=progress
	sudo /bin/sync
}

gcp() {
	git add . && git commit -S -m "$@" && git push
}

gh() {
	repo="$1"
	[ -z "$repo" ] && { echo 'usage: gh user/repo or github url' >&2; return 1; }

	repo="$(echo "$repo" | sed -E 's#https://github.com/##; s#/$##')"
	api="https://api.github.com/repos/$repo"

	auth=()
	[ -n "$GITHUB_TOKEN" ] && auth=(-H "Authorization: Bearer $GITHUB_TOKEN")
	[ -n "$GH_TOKEN" ] && auth=(-H "Authorization: Bearer $GH_TOKEN")

	r="$(curl -fsSL "${auth[@]}" "$api")" || { echo "repo not found: $repo" >&2; return 2; }
	rel="$(curl -fsSL "${auth[@]}" "$api/releases/latest" 2>/dev/null)"

	jq -n \
		--arg repo "$repo" \
		--argjson data "$r" \
		--argjson rel "${rel:-null}" '
	{
		repo: $repo,
		description: ($data.description // ""),
		stars: ($data.stargazers_count // 0),
		language: ($data.language // "?")
	}
	+ (if $rel and $rel.tag_name then {latest_tag: $rel.tag_name} else {} end)
	+ (if $rel and $rel.tarball_url then {latest_release: $rel.tarball_url} else {} end)
	'
}


hf() {
	curl -F file=@$1 https://hardfiles.org/ # yeah thats right motherfucker, real bay shit, for real bay motherfuckers.
}

mntusb() {
	sudo mount $1 /mnt -o uid=$(id -u),gid=$(id -g)
}

mkproxy() {
	PROXY_USERNAME=$(rnd 10)
	PROXY_PASSWORD=$(rnd 10)
	PROXY_PORT=$(shuf -i 40000-65535 -n 1)
	PROXY_IP=$(curl -s -4 https://maxmind.supernets.org | jq -rc .ip
	docker stop proxy>/dev/null 2>&1 && docker rm proxy>/dev/null 2>&1
	docker run -d --name proxy --restart unless-stopped -e PROXY_USER=$PROXY_USERNAME -e PROXY_PASSWORD=$PROXY_PASSWORD -e PROXY_PORT=$PROXY_PORT -p $PROXY_PORT:$PROXY_PORT serjs/go-socks5-proxy
	echo "$PROXY_USERNAME:$PROXY_PASSWORD@$PROXY_IP:$PROXY_PORT"
}

qr() {
	curl qrenco.de/$1
}

rnd() {
	cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $1 | head -n 1
}