#!/bin/sh
# TMUX Launcher - Developed by acidvegas (https://git.acid.vegas/void)

start_wildwest() {
	SESSION="WILDWEST"
	tmux new-session -d -s $SESSION -n PI
	tmux new-window -t $SESSION -n POWEREDGE
	tmux split-window -h -t $SESSION:POWEREDGE
	tmux split-window -v -t $SESSION:POWEREDGE.0
	tmux split-window -v -t $SESSION:POWEREDGE.2
	tmux send-keys -t $SESSION:POWEREDGE.0 "dbc r320-1" C-m
	tmux send-keys -t $SESSION:POWEREDGE.1 "dbc r320-2" C-m
	tmux send-keys -t $SESSION:POWEREDGE.2 "dbc r430"   C-m
	tmux send-keys -t $SESSION:POWEREDGE.3 "dbc r620"   C-m
	tmux select-layout -t $SESSION:POWEREDGE tiled
	tmux set-window-option -t $SESSION:POWEREDGE synchronize-panes on
	tmux new-window -t $SESSION -n TUNNEL
	tmux send-keys -t $SESSION:TUNNEL "dbc tunnel" C-m
	tmux attach-session -t $SESSION
}

start_supernets() {
	SESSION="SUPERNETS"
	tmux new-session -d -s $SESSION -n HUB
	tmux new-window -t $SESSION -n WILDWEST
	tmux new-window -t $SESSION -n NODES
	tmux split-window -h -t $SESSION:NODES
	tmux split-window -v -t $SESSION:NODES.0
	tmux split-window -v -t $SESSION:NODES.2
	tmux send-keys -t $SESSION:NODES.0 "dbc super-lux"     C-m
	tmux send-keys -t $SESSION:NODES.1 "dbc super-miami"   C-m
	tmux send-keys -t $SESSION:NODES.2 "dbc super-zooyork" C-m
	tmux send-keys -t $SESSION:NODES.3 "dbc super-vegas"   C-m
	tmux select-layout -t $SESSION:NODES tiled
	tmux set-window-option -t $SESSION:NODES synchronize-panes on
}

start_recon() {
	SESSION="RECON"
	tmux new-session -d -s $SESSION -n scan
	tmux new-window -t $SESSION -n box2
	tmux new-window -t $SESSION -n box3
	tmux new-window -t $SESSION -n box4
	tmux new-window -t $SESSION -n box5
	tmux attach-session -t $SESSION
}
